// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojhyckpvltbqadjwherx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaHlja3B2bHRicWFkandoZXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDg0NjIsImV4cCI6MjA3MTYyNDQ2Mn0.Q1-OJNj_JBx5GXI1OKXrxlx84P-rufH1PmdB9OEE29E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});